### ISSUE TITLE
Website doesn't display your a tokens "advanced options" if you added some when created.

### ISSUE THREAD

**Issue by GeoffedUP** [0xMithril/site#1]
The Website needs to display a created tokens "advanced options" after you create a token. My token page does not show how many tokens per block are rewarded or how many blocks are required between difficulty adjustments. I don't see it, thanks! It's working like it should though, just need it displayed 👍

**Comment by 10d9e** [comment]
Good call @GeoffedUP I will add those stats to the token page

**Comment by 10d9e** [comment]
Added newly requested fields to the token page and also fixed the icon border width
